# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

# do not run R code in vignettes
r_build_args: '--no-build-vignettes'
r_check_args: '--as-cran --ignore-vignettes'